---
### for centos <= 6
- name: install rhel sysv ezyadmin_agent init script
  copy: src=../../../files/agent/ezyadmind dest=/etc/init.d/ezyadmind owner=root group=root mode=0755
  when: ansible_distribution == "CentOS" and ( ansible_distribution_major_version == "5" or ansible_distribution_major_version == "6")

- name: enable sysv ezyadmin_agent service
  service: name=ezyadmind enabled=yes
  when: ansible_distribution == "CentOS" and ( ansible_distribution_major_version == "5" or ansible_distribution_major_version == "6")
  
- name: start ezyadmind
  service: name=ezyadmind state=started
  when: ansible_distribution == "CentOS" and ( ansible_distribution_major_version == "5" or ansible_distribution_major_version == "6")


### for centos 7
- name: install rhel sysv ezyadmin_agent init script
  copy: src=../../../files/agent/ezyadmin.service dest=/etc/systemd/system/ezyadmin.service owner=root group=root mode=0755
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  
- include: Centos7.yaml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

    
#https://techarena51.com/index.php/how-to-create-an-init-script-on-centos-6/
# systemctl daemon-reload
# systemctl start ezyadmin.service
# systemctl stop ezyadmin.service